services:
  mysqlsrv:
    image: mysql:8.0
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: "root"
      MYSQL_ROOT_PASSWORD: "1qaz@WSX"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/database/mysql/data:/var/lib/mysql